singleQuote: true
trailingComma: none
printWidth: 100
tabWidth: 2
bracketSpacing: true
importOrder:
  - ^(react/(.*)$)|^(react$)
  - ^(next/(.*)$)|^(next$)
  - <THIRD_PARTY_MODULES>
  - ''
  - ^types$
  - ^@/assets(.*)$
  - ^@/env(.*)$
  - ^@/types$
  - ^@/config/(.*)$
  - ^@/api/(.*)$
  - ^@/lib/(.*)$
  - ^@/jotai/(.*)$
  - ^@/hooks/(.*)$
  - ^@/components/(.*)$
  - ^@/styles/(.*)$
  - ''
  - '^[./]'
importOrderSeparation: false
importOrderSortSpecifiers: true
importOrderBuiltinModulesToTop: true
importOrderParserPlugins:
  - typescript
  - jsx
  - tsx
  - decorators-legacy
importOrderMergeDuplicateImports: true
importOrderCombineTypeAndValueImports: true
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
