package codes

var KeyboardMap = map[string]uint16{
	"KeyA": KeyA,
	"KeyB": KeyB,
	"KeyC": KeyC,
	"KeyD": KeyD,
	"KeyE": KeyE,
	"KeyF": KeyF,
	"KeyG": KeyG,
	"KeyH": KeyH,
	"KeyI": KeyI,
	"KeyJ": KeyJ,
	"KeyK": KeyK,
	"KeyL": KeyL,
	"KeyM": KeyM,
	"KeyN": KeyN,
	"KeyO": KeyO,
	"KeyP": KeyP,
	"KeyQ": KeyQ,
	"KeyR": KeyR,
	"KeyS": KeyS,
	"KeyT": KeyT,
	"KeyU": KeyU,
	"KeyV": KeyV,
	"KeyW": KeyW,
	"KeyX": KeyX,
	"KeyY": KeyY,
	"KeyZ": KeyZ,

	"Digit1": Key1,
	"Digit2": Key2,
	"Digit3": Key3,
	"Digit4": Key4,
	"Digit5": Key5,
	"Digit6": Key6,
	"Digit7": Key7,
	"Digit8": Key8,
	"Digit9": Key9,
	"Digit0": Key0,

	"Enter":         KeyEnter,
	"Escape":        KeyEscape,
	"Backspace":     KeyBackspace,
	"Tab":           KeyTab,
	"Space":         KeySpace,
	"Minus":         KeyMinus,
	"Equal":         KeyEquals,
	"BracketLeft":   KeyLeftBracket,
	"BracketRight":  KeyRightBracket,
	"Backslash":     KeyBackslash,
	"IntlBackslash": KeyBackslash,

	"Semicolon": KeyColon,
	"Quote":     KeyApostrophe,
	"Backquote": KeyGrave,
	"Comma":     KeyCommad,
	"Period":    KeyPeriod,
	"Slash":     Slash,
	"CapsLock":  CapsLock,

	"KeyTilde": KeyTilde,
	"KeyDot":   KeyDot,

	"F1":  KeyF1,
	"F2":  KeyF2,
	"F3":  KeyF3,
	"F4":  KeyF4,
	"F5":  KeyF5,
	"F6":  KeyF6,
	"F7":  KeyF7,
	"F8":  KeyF8,
	"F9":  KeyF9,
	"F10": KeyF10,
	"F11": KeyF11,
	"F12": KeyF12,

	"F13":         KeyPrintScreen,
	"PrintScreen": KeyPrintScreen,
	"ScrollLock":  KeyScrollLock,
	"Pause":       KeyPause,
	"Insert":      KeyInsert,
	"Home":        KeyHome,
	"PageUp":      KeyPageUp,
	"Delete":      KeyDelete,
	"End":         KeyEnd,
	"PageDown":    KeyPageDown,
	"ArrowRight":  KeyRight,
	"ArrowLeft":   KeyLeft,
	"ArrowDown":   KeyDown,
	"ArrowUp":     KeyUp,

	"NumLock":        KeyNumLock,
	"NumpadDivide":   KeyKpDivide,
	"NumpadMultiply": KeyKpMultiply,
	"NumpadSubtract": KeyKpMinus,
	"NumpadAdd":      KeyKpPlus,
	"NumpadEnter":    KeyKpEnter,
	"Numpad1":        KeyKp1,
	"Numpad2":        KeyKp2,
	"Numpad3":        KeyKp3,
	"Numpad4":        KeyKp4,
	"Numpad5":        KeyKp5,
	"Numpad6":        KeyKp6,
	"Numpad7":        KeyKp7,
	"Numpad8":        KeyKp8,
	"Numpad9":        KeyKp9,
	"Numpad0":        KeyKp0,
	"NumpadDecimal":  KeyKpPeriod,
	"KeyKpDot":       KeyKpDot,

	"ControlLeft":  KeyLCtrl,
	"ShiftLeft":    KeyLShift,
	"AltLeft":      KeyLAlt,
	"MetaLeft":     KeyLWin,
	"ControlRight": KeyRCtrl,
	"ShiftRight":   KeyRShift,
	"AltRight":     KeyRAlt,
	"MetaRight":    KeyRWin,
	"WinLeft":      KeyLWin,
	"WinRight":     KeyRWin,

	"ModifierCtrl":  ModifierLCtrl,
	"ModifierShift": ModifierLShift,
	"ModifierAlt":   ModifierLAlt,
	"ModifierMeta":  ModifierLWIN,
}
